# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='attach_file',
            field=models.FileField(blank=True, help_text='this is optional.', null=True, upload_to=b'', verbose_name='Attach File'),
        ),
    ]
